# Site settings
title: Nil Stolt Ansó

description: > # this means to ignore newlines until "baseurl:"
  My name is Nil Stolt Ansó. I am an Artificial Intelligence Master's student at the University of Amsterdam. I use this site to share my opinions on topics that I find interesting and exciting, which tend to revolve around machine learning, techonology and the mind.
baseurl: ""
url: "https://NILOIDE.github.io"
github_username:  NILOIDE

# Build settings
markdown: kramdown


